"""Add shared notes

Revision ID: 2242d78c3406
Revises: 9da9e6aa6e88
Create Date: 2024-10-02 13:35:14.084802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2242d78c3406'
down_revision = '9da9e6aa6e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_notes')
    # ### end Alembic commands ###
